<a href="https://colab.research.google.com/github/Jorge-Ruiz-Troccoli/Data-Science-I/blob/main/Clase%20002/Introducci%C3%B3n_a_Pandas_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Pandas parte I
### Coderhouse - Data Science
Profe Jorge Ruiz

Para usar una libreria y sus métodos es necesario instalarla primero. Una vez ha sido instalada es necesario importarla en el notebook en el que se va a usar.<br>

Para importar usamos el comando <code> import </code> seguido del nombre de la libreria, en la mayoria de casos se utiliza la clausula <code> as </code> para asignar un "apodo", usualmente más corto que facilite su uso.

In [ ]:
pip install yellowbrick

Requirement already satisfied: yellowbrick in /usr/local/lib/python3.12/dist-packages (1.5)
Requirement already satisfied: matplotlib!=3.0.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from yellowbrick) (3.10.0)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from yellowbrick) (1.16.3)
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from yellowbrick) (1.6.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from yellowbrick) (2.0.2)
Requirement already satisfied: cycler>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from yellowbrick) (0.12.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (1.3.3)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (2.9.0.post0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.0->yellowbrick) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.0->yellowbrick) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib!=3.0.0,>=2.0.2->yellowbrick) (1.17.0)

In [ ]:
# importar la libreria
import pandas as pd

In [ ]:
list(range(50, 70, 2))

[50, 52, 54, 56, 58, 60, 62, 64, 66, 68]

In [ ]:

Numeros = range(50, 70, 2)
Numeros_serie = pd.Series(Numeros)
Numeros_serie

0    50
1    52
2    54
3    56
4    58
5    60
6    62
7    64
8    66
9    68
dtype: int64

In [ ]:
Numeros_serie[1:8]

1    52
2    54
3    56
4    58
5    60
6    62
7    64
dtype: int64

In [ ]:
Numeros_serie.index

RangeIndex(start=0, stop=10, step=1)

In [ ]:
print(Numeros_serie.values)

[50 52 54 56 58 60 62 64 66 68]

In [ ]:
#una serie de texto
Numeros_en_texto = ['primero','segundo','tercero','cuarto','quinto','sexto','séptimo','octavo','noveno','décimo']
Numeros_serie_texto = pd.Series(Numeros_en_texto)
Numeros_serie_texto

0    primero
1    segundo
2    tercero
3     cuarto
4     quinto
5      sexto
6    séptimo
7     octavo
8     noveno
9     décimo
dtype: object

In [ ]:
Numeros

range(50, 70, 2)

In [ ]:
# una serie con index de texto y valores numericos
Numeros_en_texto = ['primero','segundo','tercero','cuarto','quinto','sexto','séptimo','octavo','noveno','décimo']
Numeros_serie_2 = pd.Series(data=Numeros,index=Numeros_en_texto, dtype='int8')
Numeros_serie_2

primero    50
segundo    52
tercero    54
cuarto     56
quinto     58
sexto      60
séptimo    62
octavo     64
noveno     66
décimo     68
dtype: int8

In [ ]:
# las series pueden contener datos de diferente tipo de formato

# Crear una serie con diferentes tipos de datos
s = pd.Series([1, 2.5, 'tres', True])

s

0       1
1     2.5
2    tres
3    True
dtype: object

In [ ]:
s.index=[5,6,8,100]
s

5         1
6       2.5
8      tres
100    True
dtype: object

In [ ]:
0#los índices pueden contener diferente tipo de datos, pandas no impone restricciones en estos casos
# 001,022, 3, 4, 9, 01
# Crear una serie con un índice mixto
#s = pd.Series(data=["001","022", "3", "4", "9"], index=['a', 1, 'b', 2, True],dtype=str)
s = pd.Series([1,"022", "3", "4", "9"], index=['a', 1, 'b', 2, True], dtype='str')
s

a         1
1       022
b         3
2         4
True      9
dtype: object

In [ ]:
modelos = ['A4 3.0 Quattro 4dr manual',
 'A4 3.0 Quattro 4dr auto',
 'A6 3.0 4dr',
 'A6 3.0 Quattro 4dr',
 'A4 3.0 convertible 2dr']
peso = [3583, 3627, 3561, 3880, 3814]
precios = ['$33,430', '$34,480', '$36,640', '$39,640', '$42,490']

In [ ]:
Autos_peso = pd.Series(data=peso,dtype=str, index=modelos)
#Autos_peso = pd.Series(peso,modelos, str)
Autos_precio = pd.Series(precios,modelos)

In [ ]:
Autos_precio

A4 3.0 Quattro 4dr manual    $33,430
A4 3.0 Quattro 4dr auto      $34,480
A6 3.0 4dr                   $36,640
A6 3.0 Quattro 4dr           $39,640
A4 3.0 convertible 2dr       $42,490
dtype: object

In [ ]:
Autos_peso

A4 3.0 Quattro 4dr manual    3583
A4 3.0 Quattro 4dr auto      3627
A6 3.0 4dr                   3561
A6 3.0 Quattro 4dr           3880
A4 3.0 convertible 2dr       3814
dtype: object

In [ ]:
Autos = pd.DataFrame(Autos_peso,Autos_precio)
Autos
# forma incorrecta de levantar el dataframe

           0
$33,430  NaN
$34,480  NaN
$36,640  NaN
$39,640  NaN
$42,490  NaN

In [ ]:
#generamos los Dataframe (df) desde las series
Autos = pd.DataFrame({'Peso':Autos_peso,'Precio':Autos_precio})
Autos

                           Peso   Precio
A4 3.0 Quattro 4dr manual  3583  $33,430
A4 3.0 Quattro 4dr auto    3627  $34,480
A6 3.0 4dr                 3561  $36,640
A6 3.0 Quattro 4dr         3880  $39,640
A4 3.0 convertible 2dr     3814  $42,490

In [ ]:
# otra forma de generar el dataframe es primero uniendo las series:

s = pd.concat([Autos_peso, Autos_precio], axis=1)
s

                              0        1
A4 3.0 Quattro 4dr manual  3583  $33,430
A4 3.0 Quattro 4dr auto    3627  $34,480
A6 3.0 4dr                 3561  $36,640
A6 3.0 Quattro 4dr         3880  $39,640
A4 3.0 convertible 2dr     3814  $42,490

In [ ]:
# Convertir la serie en un DataFrame
df = s.rename(columns={0: 'Peso_autos', 1: 'Precio'})

df

                          Peso_autos   Precio
A4 3.0 Quattro 4dr manual       3583  $33,430
A4 3.0 Quattro 4dr auto         3627  $34,480
A6 3.0 4dr                      3561  $36,640
A6 3.0 Quattro 4dr              3880  $39,640
A4 3.0 convertible 2dr          3814  $42,490

In [ ]:
#otro ejemplo de dataframe

peso= [60,70,80,None,10000]
estaturas= ["1.57", "1.68", "1.75", "1.83", None]

datos_p= pd.DataFrame({"Peso":peso, "Estaturas": estaturas})
datos_p

      Peso Estaturas
0     60.0      1.57
1     70.0      1.68
2     80.0      1.75
3      NaN      1.83
4  10000.0      None

In [ ]:
2datos_p.index= ['a','b','c','d','e']
datos_p

      Peso Estaturas
a     60.0      1.57
b     70.0      1.68
c     80.0      1.75
d      NaN      1.83
e  10000.0      None

In [ ]:
Numeros_serie_2

primero    50
segundo    52
tercero    54
cuarto     56
quinto     58
sexto      60
séptimo    62
octavo     64
noveno     66
décimo     68
dtype: int8

In [ ]:
# seleccionar usando el índice
Numeros_serie_2[2]

/tmp/ipython-input-1820232195.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Numeros_serie_2[2]

np.int8(54)

In [ ]:
#Mediante el método loc()

Numeros_serie_2.loc['quinto']

np.int8(58)

In [ ]:
Numeros_serie_2.iloc[2]

np.int8(54)

In [ ]:
#Mediante el método iloc()
Numeros_serie_2.iloc[2:6]

tercero    54
cuarto     56
quinto     58
sexto      60
dtype: int8

In [ ]:
Numeros_serie_2[2:6]

tercero    54
cuarto     56
quinto     58
sexto      60
dtype: int8

In [ ]:
datos_p.index= [2,20,5,6,7]
datos_p

       Peso Estaturas
2      60.0      1.57
20     70.0      1.68
5      80.0      1.75
6       NaN      1.83
7   10000.0      None

In [ ]:
datos_p.iloc[1:3]

    Peso Estaturas
20  70.0      1.68
5   80.0      1.75

In [ ]:
datos_p.loc[5]

Peso         80.0
Estaturas    1.75
Name: 5, dtype: object

In [ ]:
Autos

                           Peso   Precio
A4 3.0 Quattro 4dr manual  3583  $33,430
A4 3.0 Quattro 4dr auto    3627  $34,480
A6 3.0 4dr                 3561  $36,640
A6 3.0 Quattro 4dr         3880  $39,640
A4 3.0 convertible 2dr     3814  $42,490

In [ ]:
Autos2=Autos
Autos2["Peso"]=Autos2["Peso"].astype('int32')
Autos2

                           Peso   Precio
A4 3.0 Quattro 4dr manual  3583  $33,430
A4 3.0 Quattro 4dr auto    3627  $34,480
A6 3.0 4dr                 3561  $36,640
A6 3.0 Quattro 4dr         3880  $39,640
A4 3.0 convertible 2dr     3814  $42,490

In [ ]:
Autos2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A4 3.0 Quattro 4dr manual to A4 3.0 convertible 2dr
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Peso    5 non-null      int32
 1   Precio  5 non-null      object
dtypes: int32(1), object(1)
memory usage: 272.0+ bytes

In [ ]:
Autos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A4 3.0 Quattro 4dr manual to A4 3.0 convertible 2dr
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Peso    5 non-null      int32
 1   Precio  5 non-null      object
dtypes: int32(1), object(1)
memory usage: 272.0+ bytes

In [ ]:
Autos["Peso"]

A4 3.0 Quattro 4dr manual    3583
A4 3.0 Quattro 4dr auto      3627
A6 3.0 4dr                   3561
A6 3.0 Quattro 4dr           3880
A4 3.0 convertible 2dr       3814
Name: Peso, dtype: object

In [ ]:
Autos.Peso==Autos["Peso"] #son 2 formas de seleccionar columnas de la misma forma

A4 3.0 Quattro 4dr manual    True
A4 3.0 Quattro 4dr auto      True
A6 3.0 4dr                   True
A6 3.0 Quattro 4dr           True
A4 3.0 convertible 2dr       True
Name: Peso, dtype: bool

In [ ]:
Autos.loc[Autos.Peso== 3583,'Precio']
# ejemplo cuando tenemos que filtrar por str
#Autos.loc[Autos["Peso"]>= 3600,'Precio']

A4 3.0 Quattro 4dr manual    $33,430
Name: Precio, dtype: object

In [ ]:
Autos[Autos.Peso== 3583]["Precio"]

A4 3.0 Quattro 4dr manual    $33,430
Name: Precio, dtype: object

In [ ]:
Autos[Autos.Peso> 3000]["Precio"]

A4 3.0 Quattro 4dr manual    $33,430
A4 3.0 Quattro 4dr auto      $34,480
A6 3.0 4dr                   $36,640
A6 3.0 Quattro 4dr           $39,640
A4 3.0 convertible 2dr       $42,490
Name: Precio, dtype: object

In [ ]:
Autos.loc[Autos.Peso== "3583"]

                           Peso   Precio
A4 3.0 Quattro 4dr manual  3583  $33,430

In [ ]:
Autos["Peso"]= Autos["Peso"].astype("int16")
Autos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A4 3.0 Quattro 4dr manual to A4 3.0 convertible 2dr
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Peso    5 non-null      int16
 1   Precio  5 non-null      object
dtypes: int16(1), object(1)
memory usage: 262.0+ bytes

In [ ]:
1# Autos.loc[Autos["Peso"]>= 3600,'Precio']
#Autos.loc[Autos["Peso"]>= 3600]
Autos.loc[Autos["Peso"]>= 3600] #esto es igual a la primera forma

                         Peso   Precio
A4 3.0 Quattro 4dr auto  3627  $34,480
A6 3.0 Quattro 4dr       3880  $39,640
A4 3.0 convertible 2dr   3814  $42,490

In [ ]:
Autos.Peso.mean()

np.float64(3693.0)

In [ ]:
import numpy as np

np.mean(Autos.Peso)

np.float64(3693.0)

In [ ]:
Autos[Autos.Peso >=3600][["Precio", "otra column"]]

KeyError: "['otra column'] not in index"

In [ ]:
Autos.columns

Index(['Peso', 'Precio'], dtype='object')

In [ ]:
Autos.values

array([[3583, '$33,430'],
       [3627, '$34,480'],
       [3561, '$36,640'],
       [3880, '$39,640'],
       [3814, '$42,490']], dtype=object)

In [ ]:
Autos['Peso']

A4 3.0 Quattro 4dr manual    3583
A4 3.0 Quattro 4dr auto      3627
A6 3.0 4dr                   3561
A6 3.0 Quattro 4dr           3880
A4 3.0 convertible 2dr       3814
Name: Peso, dtype: int16

In [ ]:
Autos.Peso

A4 3.0 Quattro 4dr manual    3583
A4 3.0 Quattro 4dr auto      3627
A6 3.0 4dr                   3561
A6 3.0 Quattro 4dr           3880
A4 3.0 convertible 2dr       3814
Name: Peso, dtype: int16

In [ ]:
Autos["Peso"].loc["A4 3.0 convertible 2dr"]

np.int16(3814)

In [ ]:
Autos.loc[Autos.Peso >= 3600,'Precio']

A4 3.0 Quattro 4dr auto    $34,480
A6 3.0 Quattro 4dr         $39,640
A4 3.0 convertible 2dr     $42,490
Name: Precio, dtype: object

In [ ]:
type(Autos.Precio)

pandas.core.series.Series

In [ ]:
Autos.loc[Autos.Peso >= 3600]["Precio"]

A4 3.0 Quattro 4dr auto    $34,480
A6 3.0 Quattro 4dr         $39,640
A4 3.0 convertible 2dr     $42,490
Name: Precio, dtype: object

In [ ]:
Autos[Autos.Peso >= 3600]["Precio"]

A4 3.0 Quattro 4dr auto    $34,480
A6 3.0 Quattro 4dr         $39,640
A4 3.0 convertible 2dr     $42,490
Name: Precio, dtype: object

In [ ]:
Autos.T

,A4 3.0 Quattro 4dr manual,A4 3.0 Quattro 4dr auto,A6 3.0 4dr,A6 3.0 Quattro 4dr,A4 3.0 convertible 2dr
Peso,3583,3627,3561,3880,3814
Precio,"$33,430","$34,480","$36,640","$39,640","$42,490"

In [ ]:
Numeros_serie_2

primero    50
segundo    52
tercero    54
cuarto     56
quinto     58
sexto      60
séptimo    62
octavo     64
noveno     66
décimo     68
dtype: int8

In [ ]:
Numeros = range(30, 50, 2)
Numeros_serie = pd.Series(Numeros)

Numeros_en_texto = ['primeroo','segundo','tercero','cuarto','quinto','sexto','séptimo','octavo','noveno','décimo']
Numeros_serie_3 = pd.Series(Numeros,index=Numeros_en_texto)
Numeros_serie_3

primeroo    30
segundo     32
tercero     34
cuarto      36
quinto      38
sexto       40
séptimo     42
octavo      44
noveno      46
décimo      48
dtype: int64

In [ ]:
"""
Cuando se suman dos series en Python utilizando el operador +, si una serie tiene un valor NaN (Not a Number) y
la otra serie tiene un valor numérico, el resultado de la suma será NaN.

Esto se debe a que NaN representa una falta de valor o un valor desconocido, y cualquier operación matemática que
involucre NaN dará como resultado NaN. Por lo tanto, cuando se suman dos números, si uno de ellos es NaN, el resultado de
la suma también será NaN.
"""
Numeros_nan=Numeros_serie_2 + Numeros_serie_3
Numeros_nan

cuarto       92.0
décimo      116.0
noveno      112.0
octavo      108.0
primero       NaN
primeroo      NaN
quinto       96.0
segundo      84.0
sexto       100.0
séptimo     104.0
tercero      88.0
dtype: float64

In [ ]:
Numeros_serie_2.add(Numeros_serie_3)

#sub resta

cuarto       92.0
décimo      116.0
noveno      112.0
octavo      108.0
primero       NaN
primeroo      NaN
quinto       96.0
segundo      84.0
sexto       100.0
séptimo     104.0
tercero      88.0
dtype: float64

In [ ]:
# Crear la serie con el parámetro name y con nombre de índice
serie = pd.Series([10, 20, 30, 40], name='Ejemplo').rename_axis('numeros')

# Asignar un nombre al índice con rename_axis()
#serie = serie.rename_axis('Letras')

# Asignar un nombre a la columna con rename()
#serie = serie.rename('Valores')

# Imprimir la serie
serie

numeros
0    10
1    20
2    30
3    40
Name: Ejemplo, dtype: int64

In [ ]:
Numeros_nan.isnull()

cuarto      False
décimo      False
noveno      False
octavo      False
primero      True
primeroo     True
quinto      False
segundo     False
sexto       False
séptimo     False
tercero     False
dtype: bool

In [ ]:
Numeros_nan.isna()

cuarto      False
décimo      False
noveno      False
octavo      False
primero      True
primeroo     True
quinto      False
segundo     False
sexto       False
séptimo     False
tercero     False
dtype: bool

In [ ]:
Numeros_nan.info()

<class 'pandas.core.series.Series'>
Index: 11 entries, cuarto to tercero
Series name: None
Non-Null Count  Dtype
--------------  -----
9 non-null      float64
dtypes: float64(1)
memory usage: 476.0+ bytes

In [ ]:
Numeros_nan.fillna(-999)
#Numeros_nan= Numeros_nan.fillna(-999)

cuarto       92.0
décimo      116.0
noveno      112.0
octavo      108.0
primero    -999.0
primeroo   -999.0
quinto       96.0
segundo      84.0
sexto       100.0
séptimo     104.0
tercero      88.0
dtype: float64

In [ ]:
Numeros_nan.fillna(Numeros_nan.mean())

cuarto       92.0
décimo      116.0
noveno      112.0
octavo      108.0
primero     100.0
primeroo    100.0
quinto       96.0
segundo      84.0
sexto       100.0
séptimo     104.0
tercero      88.0
dtype: float64

In [ ]:
Numeros_nan=Numeros_nan.dropna()
Numeros_nan

cuarto      92.0
décimo     116.0
noveno     112.0
octavo     108.0
quinto      96.0
segundo     84.0
sexto      100.0
séptimo    104.0
tercero     88.0
dtype: float64

In [ ]:
Numeros_nan.isnull()

cuarto     False
décimo     False
noveno     False
octavo     False
quinto     False
segundo    False
sexto      False
séptimo    False
tercero    False
dtype: bool

In [ ]:
Numeros_nan.isnull().sum()

np.int64(0)

In [ ]:
Numeros_nan.isna().sum()
#puede usar .isna()  o . isnull()

np.int64(0)

In [ ]:

df= pd.read_csv('pokemon_data.txt',delimiter='\t', index_col=0, dtype={'HP':str})
df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [ ]:
df.head()

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 800 entries, 1 to 721
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        800 non-null    object
 1   Type 1      800 non-null    object
 2   Type 2      414 non-null    object
 3   HP          800 non-null    object
 4   Attack      800 non-null    int64
 5   Defense     800 non-null    int64
 6   Sp. Atk     800 non-null    int64
 7   Sp. Def     800 non-null    int64
 8   Speed       800 non-null    int64
 9   Generation  800 non-null    int64
 10  Legendary   800 non-null    bool
dtypes: bool(1), int64(6), object(4)
memory usage: 69.5+ KB

In [ ]:
df[(df.HP>30)&(df.Attack>80)]

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,
3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [ ]:
len(df[df["Type 1"]=="Fire"])

52

In [ ]:
df["peso"]

In [ ]:
df.isnull().sum()

Name            0
Type 1          0
Type 2        386
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [ ]:
df["Type 2"].fillna("ES DE UN SOLO TIPO", inplace=True)

/tmp/ipython-input-2136170338.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Type 2"].fillna("ES DE UN SOLO TIPO", inplace=True)

In [ ]:
df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,ES DE UN SOLO TIPO,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [ ]:
df.index

In [ ]:
df.head(3)

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False

In [ ]:
df.columns

In [ ]:
df.shape

(800, 11)

In [ ]:
df.size

8800

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 800 entries, 1 to 721
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        800 non-null    object
 1   Type 1      800 non-null    object
 2   Type 2      414 non-null    object
 3   HP          800 non-null    int64
 4   Attack      800 non-null    int64
 5   Defense     800 non-null    int64
 6   Sp. Atk     800 non-null    int64
 7   Sp. Def     800 non-null    int64
 8   Speed       800 non-null    int64
 9   Generation  800 non-null    int64
 10  Legendary   800 non-null    bool
dtypes: bool(1), int64(7), object(3)
memory usage: 69.5+ KB

In [ ]:
df['Type 2'].isna().sum()

In [ ]:
df['Type 2'].isnull().sum()

In [ ]:
df['Type 2'].isnull().sum()==df['Type 2'].isna().sum()